### ISSUE TITLE
[1.16.4] Umbrella gravity crash report

### ISSUE THREAD

**Issue by Fogrits** [florensie/artifacts-fabric#1]
[Crash Report](https://pastebin.com/2S94F93m)

Artifacts 1.0.1

**Comment by florensie** [comment]
Hey could you give me your entire game log? This should be an incompatibility with another mod.

**Comment by Fogrits** [comment]
I couldn't reproduce it after updating to 1.0.2

**Comment by florensie** [comment]
Ok, feel free to revive this issue if you get the same crash.

**Comment by Fogrits** [comment]
Oh, I managed to get the crash again.
And now I managet to get a crash log.

[Crash Report](https://pastebin.com/W74kQ1db)

**Comment by florensie** [comment]
Thanks, I'll look into it.

**Comment by florensie** [comment]
I take it this crash happens while starting the game? But it doesn't happen every time?

**Comment by Fogrits** [comment]
Seems so.

**Comment by florensie** [comment]
Ok, this seems like a weird one. It might take me a little while to figure this out.

**Comment by florensie** [comment]
It turned out to be pretty easy to find actually. It's an incompatibility with Tic-TACS due to a mixin quirk.
It's fixed and will be included in the next release (might take a bit though).
