### ISSUE TITLE
Whoopee Cushion crashes server

### ISSUE THREAD

**Issue by ImJustMatt** [florensie/artifacts-fabric#14]
When I updated to Artifacts-2.0.0+1.16.4-fabric.jar, I had the whoopee cushion effect even though I didn't have the item. I tried giving myself the whoopee cushion to activate/deactivate it, and upon trying to use it (SHIFT+Right Click) my server immediately crashed.

https://gist.github.com/ImJustMatt/f2e54c8f187b3b7644f338b64f6df765

**Comment by florensie** [comment]
Thanks, just fixed both issues.
