### ISSUE TITLE
and another thing... umbrellas again... also origins compat again

### ISSUE THREAD

**Issue by superon** [florensie/artifacts-fabric#19]
**Is your feature request related to a problem? Please describe.**
there is an origin condition where players become vulnerable to being wet, be it by being in water blocks or being rained on, players in this situation tend to see the umbrella an think it their saviour until they try it, it has been upsetting.

**Describe the solution you'd like**
could we have the umbrella negate the "origins:in_rain" player condition when not being used as a shield?

**Describe alternatives you've considered**
i've consider renaming Umbrella to Parasol... though i fear this will only shift the issue onto those with vulnerability in sunlight due to origins:exposed_to_sun. 

**Additional context**
actually no i mention it, i do feel like it could be used to prevent both.   and now i mention that i do wonder if this is something i should be attempting to implement myself with a datapack :)

**Comment by florensie** [comment]
I found a really nice solution to the `in_rain` condition. It has the side effect of influencing a lot of other vanilla effect to being in the rain/wet like conduit power, tridents and extinguishing yourself.

Not sure what to do about `origins:exposed_to_sun` yet, if anything at all. I'll look into it tomorrow.

**Comment by florensie** [comment]
`exposed_to_sun` should work right away in the latest release, but `in_rain` requires this PR to be merged on Origin's side: apace100/origins-fabric/pull/60
