### ISSUE TITLE
Conflict with the inmist mod

### ISSUE THREAD

**Issue by Romz24** [florensie/artifacts-fabric#20]
I already reported this bug [here](https://github.com/Draylar/inmis/issues/59), but it looks like they are not going to do anything about it.

The essence of the error lies in the fact that I cannot use the slot for the neck and the backpack at the same time, these slots are reversed. Can you fix this?

Video: https://youtu.be/0SzVJ9wzl2U

Minecraft: 1.16.5
Inmis: [2.1.2](https://www.curseforge.com/minecraft/mc-mods/inmis/files/3223401)
Artifact: [2.3.0](https://www.curseforge.com/minecraft/mc-mods/artifacts-fabric/files/3181022)
Trinkets: [2.6.7](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric/files/3100959)

**Comment by florensie** [comment]
Looks like a bug with Trinkets at first glance but I'll have to take a closer look later.

**Comment by florensie** [comment]
Ok so I took a good look and there's two things I noticed here.

1. In your video, you can place your items in the slot for just a split second and then it pops back
2. In your video, your scarf disappears at some point but reappears after you rejoin
3. When I tested this the necklace and backpack slots were swapped the other way around 

All of this likely means that it's a desync issue. I think what's happening is that your client and the server have the slots the other way around. This means that if you place an item in the necklace slot on your client that it will go in the backpack slot on the server (and the other way around).

I'll open an issue with Trinkets.
