### ISSUE TITLE
Crash with Transliterationlib

### ISSUE THREAD

**Issue by GeradesoLukas** [florensie/artifacts-fabric#21]
**Describe the bug**
The Game Crashes when starting

**To Reproduce**
1. Download the latest Version of Transliterationlib
2. Use it together with Artifacts

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Minecraft: 1.16.5
 - Fabric API: 0.31.0
 - Artifacts: 3.0.3
- Transliterationlib: https://www.curseforge.com/minecraft/mc-mods/transliterationlib

**Comment by florensie** [comment]
Thanks, I'll look into it.

**Comment by florensie** [comment]
Could you provide a crash log? It doesn't appear to crash for me.

**Comment by GeradesoLukas** [comment]
[crash-2021-03-21_14.30.32-client.txt](https://github.com/florensie/artifacts-fabric/files/6177499/crash-2021-03-21_14.30.32-client.txt)
Sorry I didn't have the time to go back here ^^"
This should be it. There might be another Mod involved

**Comment by florensie** [comment]
I accidentally found the same crash earlier today and has nothing to do with TranslaterationLib (not sure where you got that from). It's an incompatibility with canvas. The fix will be included in the next release.
