### ISSUE TITLE
Add compatibility with the backslot mod

### ISSUE THREAD

**Issue by Kelavus** [florensie/artifacts-fabric#23]
When using both artifacts and backslot the inventory slot for the gauntlet above the shield slot is covering the belt slot for the backslot mod. Maybe do something similar to the other slot which only shows up when hovering over the shield slot and have that be how you access both gauntlets.

**Comment by florensie** [comment]
This is an issue with Trinkets or Backslots, not Artifacts.

**Comment by Rocco155** [comment]
I found out, that you can shift the backslot slots up in the configs of backslot, by putting y= -16 in the configs, just in case someone encounters this problem.
