### ISSUE TITLE
Cloud in a Bottle used with Bunny Hoppers may need tweaking

### ISSUE THREAD

**Issue by saltyseadoggo** [florensie/artifacts-fabric#27]
**Describe the bug**
When a player uses the cloud in a bottle's double jump while sprinting, they can jump much higher than when not. Normally, one can jump about 2.5 blocks with the double jump; while sprinting, this is about four. This gets crazier with the bunny hoppers: normally, one can jump about 5.5 blocks with the slippers and cloud, but, while sprinting, this becomes about 8.5.
Given how ridiculous an eight block jump height is, I figure that this is likely not intended, and that sprinting should not increase the second jump's height.
I checked to make sure that a higher jump height while sprinting was not to blame, and sprinting does not make a player jump higher. "While sprinting, it is possible to jump across up to four blocks horizontally,[1] instead of the usual two blocks, although **sprinting does not cause the player to jump higher.**" - [Minecraft Wiki](https://minecraft.fandom.com/wiki/Sprinting)

**To Reproduce**
1. Create a new world.
2. Assemble this smooth stone structure with some blocks in front for jumping/sprinting on:
![2021-05-04_13 37 21](https://user-images.githubusercontent.com/69029346/117066695-e71b2d80-acdd-11eb-8d88-8ad0545c7841.png)
3. Equip the cloud in a bottle and enter survival or adventure mode.
4. Double jump without sprinting, and you should be able to scale the leftmost height on the structure.
5. Double jump while sprinting, and you should clear the second to leftmost.
6. Equip the bunny hoppers.
4. Double jump without sprinting, and you should be able to scale the second to rightmost height on the structure.
5. Double jump while sprinting, and you should clear the rightmost.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Minecraft: 1.16.5
 - Fabric API: 0.32.5
 - Artifacts: 3.2.0
 - Trinkets: 2.6.7
 - All of Fabric 3 modpack: 2.7.2

**Comment by florensie** [comment]
I appreciate the effort and detail you put into this bug report, but this behaviour is intended.

https://github.com/florensie/artifacts-fabric/blob/6b2e786d91eb47642ba66c5614257f7d3de26203/src/main/java/artifacts/mixin/mixins/item/cloudinabottle/LivingEntityMixin.java#L127

As your issue suggests, there might still be some unexpected behaviour when using Bunny Hoppers together with a Cloud in a Bottle. I'm not too sure if the Bunny Hoppers affect your second jump, and whether they should. I'll look into it and compare with the Forge version of the mod, your structure should come in handy for that.

**Comment by saltyseadoggo** [comment]
Groovy. I gave the issue a new name to reflect what you're looking into.

**Comment by ochotonida** [comment]
I'm planning on rebalancing some artifacts in the future. In the meantime, version 8.0.0/9.0.0 add game rules which can be used to change the effects of artifacts, including the extra jump height/distance you get from the cloud in a bottle while sprinting
