### ISSUE TITLE
Config to disable bunny hoppers fall damage immunity

### ISSUE THREAD

**Issue by saltyseadoggo** [florensie/artifacts-fabric#28]
**Is your feature request related to a problem? Please describe.**
I find the bunny hoppers' fall damage immunity power to be a little bit busted. Suddenly, you can leap off of mountains, high ledges in the Nether,, End cities, etc. with no penalty. I personally find needing to approach these situations with caution, as well  as the effective desirability of the Feather Falling enchantment, slow falling potions or skill with the elytra, to be more engaging than just being immune to the damage at no real cost to the player aside from needing to find the hoppers.
While there are a handful of trinkets that are *x potion effect but permanent,* this is the only one that outright cancels a source of damage with no cost of skill or resources to the player, which is why I feel it to be out of line.
This is, of course, a matter of opinion, which is why I would like to suggest...

**Describe the solution you'd like**
... a config option to disable the bunny hoppers' fall damage immunity. This way, they would still retain their jump height power without the fall damage immunity for players who find it undesirable.

**Describe alternatives you've considered**
- If you added this effect because the added jump height makes one more prone to fall damage when, say, jumping on the gentle slopes in plains biomes, then you could have this config option swap the immunity with mere resistance to fall damage, akin to, say, one level of Feather Falling, or increase the number of blocks the player can fall before fall damage starts applying from three to four to negate the added risk. It is important that the effect does not stack with the Feather Falling enchantment to create Feather Falling IV, which reintroduces fall damage immunity.
- If you for some reason think that the fall damage immunity is too much for the mod as a whole, then the above could be an alternative.

**Comment by florensie** [comment]
Seems like a reasonable request. The next Forge version is already getting loads more config options (including this one) so I'll probably have a config update too.

Feather Falling style behaviour seems like a viable option too.

**Comment by ochotonida** [comment]
A game rule to disable fall damage immunity was added in version 8.0.0/9.0.0
