### ISSUE TITLE
Cosmetic Toggles

### ISSUE THREAD

**Issue by AmyMialee** [florensie/artifacts-fabric#31]
**Is your feature request related to a problem? Please describe.**
It would be nice to have some way to disable the artifacts visually, they can be annoying in how they clash with other cosmetics.

**Describe the solution you'd like**
Toggling them through an extra options menu like the skin menu would be ideal, since it would be easy to toggle on the fly and player specific.

**Comment by Rocco155** [comment]
Yes please!

**Comment by Rocco155** [comment]
Or combining them with "invisibility ink" to disable the rendering. Was nice in Botania.

**Comment by Dr-Tarantula** [comment]
Can this feature be added to 1.16.5 or are they receiving no further updates?

**Comment by florensie** [comment]
It's a solid not for 1.16.5 support, sorry.

**Comment by florensie** [comment]
Added in ea03c1c60c4d760854a49ea3b45f047b86ff4aa3
