### ISSUE TITLE
Artifacts don't work properly with Armorstands

### ISSUE THREAD

**Issue by d4rkm0nkey** [florensie/artifacts-fabric#33]
**Artifacts can not be equipted to armor stands properly.**
As shown in the CurseForge mod page of the Forge mod, Artifacts should be equipable to armor stands.
When I right click with the drinking hat or the Villager head, it will not be equipted to the head slot of the armor stand.
The umbrella works for armor stands with hands, but is facing downwards.

**To Reproduce**
1. Install Artifacts
2. Place armor stand
(3.) Optional: Type `/data merge entity @e[type=armor_stand,limit=1,sort=nearest] {ShowArms:true}` to give arms to the armor stand.
4. Try to place various Artifacts on the armor stand.
5. See error

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Minecraft: 1.16.5
 - Fabric API: 0.34.6+1.16
 - Artifacts: v3.2.1+fabric
 - Trinkets: v2.6.7

**Comment by ochotonida** [comment]
It's actually not Artifacts that allows armor stands to wear artifacts, it's [Curious Armor Stands](https://www.curseforge.com/minecraft/mc-mods/curious-armor-stands). Unfortunately creating a similar mod for trinkets is not possible due to technical limitations of the 1.16 version of Trinkets.

**Comment by florensie** [comment]
To add to what @ochotonida said: I plan to make an alternative to Curios Armor Stands for the 1.17 version of Trinkets.
