### ISSUE TITLE
Crash with component registration

### ISSUE THREAD

**Issue by irunatbullets** [florensie/artifacts-fabric#35]
**Describe the bug**
A player with flippers in a backpack crashed the server every time they joined. 

**To Reproduce**
I'm not sure how to reproduce. We have had a few random artifacts crashes, but they're usually resolved after a reboot. In this case it kept occurring.

https://paste.alloffabric.com/esaxorofog.yaml

Hmm, I'm not sure if this belongs here or with CCA.

**Comment by florensie** [comment]
It's most likely an issue with CCA. The exception in the crash log you provided should be the cause of an earlier exception. Unless you have a full log that has that initial exception in it (which it might not) then I or the CCA devs can't do much about it unfortunately.
