### ISSUE TITLE
Occasional crash when loading new chunks (feature placement)

### ISSUE THREAD

**Issue by cecaelion** [florensie/artifacts-fabric#36]
**Describe the bug**
Occasionally, the game crashes when I attempt to enter a new chunk, citing a problem with feature placement. Both Blame and Not Enough Crashes indicate that Artifacts is the cause. 

This only happens if I enter the chunk from one direction. If I loop back to the chunk that originally caused the issue and enter it from elsewhere, it usually works. I would attempt to reproduce the error with fewer mods to see if it's a conflict, but since it doesn't seem to be consistent, I'm not sure how I would do that. It's happened with slightly different mod configurations. 

**To Reproduce**
It happens at complete random, so I can't replicate it. I backed up the version of my save right before I was going to enter the problematic chunk, so if you think I should upload it (along with a list of the mods I'm using), I'll do that.

**Game Environment**
 - Minecraft: 1.16.5
 - Fabric API: 0.37.0
 - Artifacts: 3.2.1
 - Trinkets: 2.6.7
 - Windows 10 x64, 8 GB RAM, 4 GB maximum allotted to Minecraft, launching via MultiMC
 - More details in the logs, since I've been messing with mod set-ups to figure out exactly how I want to play.
 - [Crash log 1](https://pastebin.com/Xd2yeUsg) (July 19th)
 - [Crash log 2](https://pastebin.com/FBwxsuxq) (July 23rd)
 - [Crash log 3](https://pastebin.com/FBwxsuxq) (July 29th)

Thanks in advance! This is one of my favorite mods so it's frustrating when it causes problems. I tried looking to see if anyone else has had this problem, but I don't see any other reports of issues with feature placement.

**Comment by florensie** [comment]
Just so you know, the links for crash log 2 & 3 are the same. From looking at the logs real quick it could be an issue with "Overworld Two", can you try running your game without it?

**Comment by cecaelion** [comment]
After getting a crash based on Vanilla structure placement, I turned off Overworld Two and I haven't experienced the issue since. Thanks so much!

**Comment by florensie** [comment]
Great to hear, thanks for reporting back.
