### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Romz24** [florensie/artifacts-fabric#37]
**Describe the bug**
After updating the mod, the game crashes on launch.

**To Reproduce**
1. Download the mod
2. Install the mod
3. Go to the game

**Game Environment**
 - Minecraft: 1.16.5
 - Fabric API: 0.40.1
 - Artifacts: 4.0.0
 - Trinkets: 2.6.7
 
**File log**
Unfortunately, there is no crash log because it is not created, there is only a game launch log.
[latest.log](https://github.com/florensie/artifacts-fabric/files/7248492/latest.log)

**Comment by florensie** [comment]
Looks like a mixin conflict with The Aether, I'll look into it.

**Comment by florensie** [comment]
Must be resolved on Aether's side.

**Comment by Romz24** [comment]
It's a pity, as far as I understand, Aether mod will no longer be updated for version 1.16.5, but will only be updated for 1.17

**Comment by florensie** [comment]
I'll see if I can't find a way around the issue for 1.16 then.

**Comment by florensie** [comment]
Should be fixed in the latest version of ExpandAbility, which is included in patch v4.0.1 of Artifacts

**Comment by Romz24** [comment]
Unfortunately the game still keeps crashing on launch.

File: [latest.log](https://github.com/florensie/artifacts-fabric/files/7281862/latest.log)

**Comment by florensie** [comment]
That's not the same issue, it's crashing due to a mixin conflict with randompatches. You might be able to disable those patches individually if that mod allows it, it should be one related to keybinds.

**Comment by Romz24** [comment]
I decided to test, and found at least 2 mods due to which the game crashes on startup.
I removed all mods completely, leaving only the most important ones. Installing these mods separately will crash loading the game. I noticed that crash errors differ depending on which mod I install, so I uploaded 2 logs.

- **mousewheelie**: [latest.log](https://github.com/florensie/artifacts-fabric/files/7289534/latest.log)
- **randompatches**: [latest.log](https://github.com/florensie/artifacts-fabric/files/7289532/latest.log)


My mods list:
```
artifacts-4.0.1+fabric.jar
cloth-config-4.11.26-fabric.jar
fabric-api-0.40.1+1.16.jar
trinkets-2.6.7.jar

mousewheelie-1.7.3-newconfig.3+mc1.17.1-pre1.jar
or
randompatches-2.4.5-fabric.jar
```

**Comment by florensie** [comment]
Please resume discussion here: https://github.com/florensie/ExpandAbility/issues/2

**Comment by florensie** [comment]
Previous fix for compatiblity with the Aether has been pulled, as it did not work correctly. Has to be fixed by The Aether, no other way around this.
