### ISSUE TITLE
Umbrella not blocking origins:exposed_to_sun condition with origins datapack

### ISSUE THREAD

**Issue by nemvy** [florensie/artifacts-fabric#38]
**Is your feature request related to a problem? Please describe.**
I have noticed that the umbrella item works to block out the sun for the vampire origin mod, however when I tried it with the demon origin mod, I have no such luck.

**Describe the solution you'd like**
A feature in the umbrella item to block out the sun so it can work with the demon origin mod.

**Comment by florensie** [comment]
Taking a quick look at that mod it uses the same functionality as origins, so it should already work as-is. Please provide specifics on how to reproduce your use-case, including the expected and actual behaviour.

**Comment by florensie** [comment]
Closing for lack of details.
