### ISSUE TITLE
Crash in ServerPlayerGameModeMixin

### ISSUE THREAD

**Issue by EsFredderick** [florensie/artifacts-fabric#43]
**Describe the bug**
When you create a new world, the game crashes. That's it.

**To Reproduce**
1. Go to 'Singleplayer'
2. Delete all current world saves (or just skip this step and go to step 3)
3. Create a new world
4. See the error appears

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Minecraft: [1.17.1]
 - Fabric API: [0.40.8]
 - Artifacts: [5.02.]
 - Trinkets: [3.0.4]
 - A lot of other mods, I don't know if it could help but [here](https://docs.google.com/uc?export=download&id=17QvkH475SSHCvBmBjM9-67rjFq2suZTj) is the crash log.

**Comment by florensie** [comment]
I can't remember if I did anything to fix this but it probably works now. Let me know if this is still an issue.
