### ISSUE TITLE
Improve configurability

### ISSUE THREAD

**Issue by florensie** [florensie/artifacts-fabric#44]
See config options available in Forge version

**Comment by Abalieno** [comment]
Kind of ironical this important part of usability was never added to Fabric.

**Comment by ochotonida** [comment]
Fixed in version 8.0.0/9.0.0

**Comment by Abalieno** [comment]
Heh, but 19.4 is useless and 1.20 not yet viable for modpacks.

Everyone is still on 19.2.

**Comment by ochotonida** [comment]
I understand that many players are still using 1.19.2. However, backporting and maintaining all features from the latest version of the mod is unfortunately not something I have the time for.
