### ISSUE TITLE
Crash with RandomPatches

### ISSUE THREAD

**Issue by Fade-Alchemist** [florensie/artifacts-fabric#46]
I am playing fabric- Minecraft version 1.16.5. When I use artifacts-3.2.1+fabric.jar it works. When I use any update beyond that, Minecraft crashes during launch with error code "0".

**Comment by florensie** [comment]
Please provide your minecraft logs.

**Comment by Fade-Alchemist** [comment]
I have the most up to date  version of Fabric API fabric-api-0.40.6+1.16.jar this is for Minecraft version 1.16.5
the error log: https://pastebin.com/iTSCS88A

**Comment by Fade-Alchemist** [comment]
I have gone to your RandomPatches#247 link, it references an incompatibility with ExpandAbility. Excuse me if I am being dense, but I don't see how this has anything to do with the issue I am reporting as ExpandAbility is not in my mod pack...

**Comment by Fade-Alchemist** [comment]
Thank you for the explanation. 👍
