### ISSUE TITLE
artifacts.components.EntityKillTrackerComponent crash on join world edge-case?

### ISSUE THREAD

**Issue by superon** [florensie/artifacts-fabric#50]
**Describe the bug**
joining this previously loaded world (created before removing random patches and updating artifacts) appears to cause a crash
https://pastebin.com/ETLs7vLE

**To Reproduce**
Steps to reproduce the behaviour:
1. load world

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Minecraft: [1.16.5]
 - Fabric API: [0.42.0+1.16]
 - Artifacts: [4.0.2+fabric]
 - Trinkets: [2.6.7]
 - [other relevant mods maybe in crashlog]

**Comment by florensie** [comment]
Seems like something created an invalid nbt namespace somehow. Not sure what could have caused this but if it is an issue with Artifacts, it might be fixed when I drop `EntityKillTrackerComponent` in the next update.

**Comment by superon** [comment]
<3 also seeing this, though i'm not sure i didn't make this one happen
01.12 02:19:09 [Server] Server thread/WARN Failed to deserialize component: unregistered key artifacts:trinket_enabled

server console spam

**Comment by irunatbullets** [comment]
Apparently there's been a bit of pain for the server admins on our last remaining AOF3 server regarding this issue. They're working around it at the moment by just removing the lastKilledEntities tag from players who can't join. Is there possibly another way that they could resolve that without editing player data maybe?

**Comment by florensie** [comment]
Should be fixed in v4.0.3.
