### ISSUE TITLE
Artifacts 7.0.0 crashes while starting the game

### ISSUE THREAD

**Issue by Rymka69** [florensie/artifacts-fabric#58]
**Describe the bug**
Game crashes while loading into the game. Only using artifacts-7.0.0 and required dependencies (tried with and without ModMenu).

**To Reproduce**
1. Installed fabric 0.13.3-1.18.2
2. In the mods folder dropped Artifacts mod file and (only) required dependencies (tried running with and without ModMenu)
3. Launch Game, crashes
[2022-04-10-7.log](https://github.com/florensie/artifacts-fabric/files/8457845/2022-04-10-7.log)

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Minecraft: 1.18.2
 - Fabric API: 0.48.0
 - Artifacts: 7.0.0
 - Trinkets: 3.3.0
 - Fabric: 0.13.3-1.18.2
 - deleted other mods to avoid extra issues

**Comment by florensie** [comment]
Caused by issue in fabric-loom https://github.com/FabricMC/fabric-loom/issues/611

Luckily I can simply remove the mod's use of that feature.
