### ISSUE TITLE
[BUG] rei_plugin is deprecated and incompatible with a newer version of REI

### ISSUE THREAD

**Issue by CoolNerfDude** [florensie/artifacts-fabric#67]
Probably just change the entry point for rei_plugin to rei_client

here's a screenshot,
_______________
![Screenshot (12)](https://user-images.githubusercontent.com/82691706/173684366-ce3ceb16-6f5f-4738-9b60-6eb59ef2b4c1.png)

**Comment by florensie** [comment]
Thanks for the warning, I take it this is in 1.19?

**Comment by CoolNerfDude** [comment]
Yea its for 1.19
