### ISSUE TITLE
[1.18.2/1.19] Artifact's Mimic Compat

### ISSUE THREAD

**Issue by ConqAra** [florensie/artifacts-fabric#69]
Artifact's mimics will just show as normal chests when using myloot, which is obvious that their mimics. Is there a way to add compat for myloot when observing mimic chests? [I also posted this issue on the myloot github](https://github.com/spoorn/myLoot/issues/21).

**Comment by ConqAra** [comment]
I didn't realize they also had a forge version, I'll just throw it over there again.

**Comment by florensie** [comment]
https://github.com/ochotonida/artifacts/issues/153

**Comment by florensie** [comment]
There doesn't appear to be a forge version as far as I can see. Where did you find this?

**Comment by florensie** [comment]
Added in a88a154c, let me know if you can find that Forge version, but I think you are mistaken ;)
