### ISSUE TITLE
[1.19 Fabric][Bug] Artifacts disappear after death in less than 5 minutes.

### ISSUE THREAD

**Issue by MrJorman** [florensie/artifacts-fabric#72]
After the player's death, artifacts disappear in less than 5 minutes. When I installed Carpet-minitweaks and set the value of deathItemsdespawn = 15 minutes, then all my items, except artifacts, disappeared after 15 minutes, but artifacts disappear for some reason faster.. fix it!

**Comment by MrJorman** [comment]
I do not know what needs to be fixed here in this case, the Artifacts mod, Trinkets or carpet-fixes. But my players complain that when they die, the artifacts that they were wearing or were in the 2nd hand disappear in 5 minutes, even if the player is not in the chunks.

**Comment by florensie** [comment]
Does this only happen with artifacts, or also trinket items from other mods?

**Comment by MrJorman** [comment]
All trinkets, Loot Warden too items disappear.

**Comment by florensie** [comment]
Then it's obviously not an issue with Artifacts.

**Comment by MrJorman** [comment]
> Then it's obviously not an issue with Artifacts.

fix umbrella .

**Comment by florensie** [comment]
That's unrelated to this issue.
