### ISSUE TITLE
Conflicting Mods: Death grave glitch!

### ISSUE THREAD

**Issue by CHERRYRACHH** [florensie/artifacts-fabric#74]
**Describe the bug**
I am playing multiplayer with my partner and every time I hit him and die from it because he's wearing the "Thorns Pendant", I lose all my items. We use the "You're in Grave Danger" mod and it doesn't drop my gravestone, thus losing all items.

**To Reproduce**
1. Have the other player wearing the Thorns Pendant
2. Hit them
3. Die.
4. Spawn back and go to last death spot and don't see Gravestone.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Please provide exact version numbers, "latest" is not enough.
 - Minecraft: 1.19
 - Modpack: Dreamcraft 1.0.21
 - Fabric API: fabric-api-0.58.0+1.19
 - Artifacts: artifacts-7.1.1+fabric
 - Trinkets: trinkets-3.4.0
 - Youre In Grave Danger: youre-in-grave-danger-1.4.1

**Comment by florensie** [comment]
This would be either an issue with Youre In Grave Danger or Trinkets.
