### ISSUE TITLE
Is Everlasting Beef properly dropping?

### ISSUE THREAD

**Issue by Birgliss** [florensie/artifacts-fabric#8]
I have a pretty big cow farm, and I found it pretty odd that I hadn't found any everlasting beef in all my playtime.

So, I booted up a burner instance with just Artifacts (and dependencies), replaced the injected loot_table [with this](https://gist.github.com/Birgliss/06684059514d09b913c8def1646a09d0), and there is still no beef dropping.
[This is the datapack i'm using, if you'd like to test it.](https://github.com/florensie/artifacts-fabric/files/5544123/test.zip)

Using Artifacts version 1.1.0 on Minecraft 1.16.4. Am I missing something obvious?

**Comment by florensie** [comment]
The path should be `my_datapack/data/artifacts/loot_tables/inject/entities/cow.json`, you put the `assets` directory in this directory structure as well.

This works for me: [test.zip](https://github.com/florensie/artifacts-fabric/files/5546016/test.zip)

**Comment by Birgliss** [comment]
Oof 😅 I *was* missing something obvious.
