### ISSUE TITLE
Getting "Error loading class:" warning when loading server

### ISSUE THREAD

**Issue by Killasaurus-Warbear** [florensie/artifacts-fabric#80]
**Describe the bug**
When running a server with only Artifacts, Cloth Config, Trinkets, and Forge API I get the following warnings: 

`[19:27:07] [main/WARN]: Error loading class: io/github/apace100/apoli/power/factory/condition/ConditionFactory (java.lang.ClassNotFoundException: io/github/apace100/apoli/power/factory/condition/ConditionFactory)`
`[19:27:07] [main/WARN]: @Mixin target io.github.apace100.apoli.power.factory.condition.ConditionFactory was not found mixins.artifacts.json:compat.origins.ConditionFactoryAccessor from mod artifacts`

**To Reproduce**

1. Launch 1.19.2 server with the latest 1.19.2 mods Artifacts, Cloth Config, Trinkets, and Forge API.
2. Above warnings will be thrown

Removing just Artifacts and leaving the other mods stops the warnings.

**Comment by florensie** [comment]
This warning is logged by Mixin, but it's completely harmless. Nothing I can do about it.
