### ISSUE TITLE
Right ear in right leg for bunny hoppers is not showing like in the banner from CurseForge, left leg ears are fine

### ISSUE THREAD

**Issue by daxthin** [florensie/artifacts-fabric#82]
https://github.com/florensie/artifacts-fabric/blob/8a87b1771783140921d5644c9068af7f01620c41/src/main/java/artifacts/client/render/curio/model/LegsModel.java#L137

child identifier should be right_leg instead of left_leg

![2023-03-02_15 51 03](https://user-images.githubusercontent.com/78769008/222524247-f5eee846-f4fc-433a-94c7-cea18c232d0a.png)

![2023-03-02_15 52 18](https://user-images.githubusercontent.com/78769008/222524314-4c2a9f31-4dfe-4c2f-aac0-91a6be8272f4.png)

**Comment by florensie** [comment]
You're right. Seems like a bad copy paste job.

**Comment by ochotonida** [comment]
Seems like this issue also exists on the Forge version, no idea how this went undetected for 2 years.

**Comment by daxthin** [comment]
It's normal for this to happen when there is a lot of code. It seems that the people at CurseForge didn't realize that the rabbit ear was missing and nobody reported it. 

I will close the issue now. Thank you guys!

**Comment by florensie** [comment]
I'm going to keep it open until I get around to fixing it. I'll definitely forget otherwise. 😉

**Comment by ochotonida** [comment]
Fixed in version 8.0.0/9.0.0
