### ISSUE TITLE
Ability to Toggle the rendering of the Artifacts

### ISSUE THREAD

**Issue by suuty** [florensie/artifacts-fabric#88]
It would be very nice as some of the models are very odd looking and jarring

Solution:
A simple toggle rendering button or config option that is featured in other mods

**Comment by ochotonida** [comment]
You can already toggle visibility by right-clicking the item in your inventory. I'll probably look into improving this a bit in the future though, since right now it's not really clear this exists. Best case scenario Trinkets just adds a button for this.
