### ISSUE TITLE
Goggles making render bug

### ISSUE THREAD

**Issue by Aflaungos** [florensie/artifacts-fabric#9]
In Minecraft 1.16.3, whenever I equip goggles text screen and item icons go black, this happened after I stayed too much under water

**Comment by florensie** [comment]
Any chance you have a log?

**Comment by Aflaungos** [comment]
How do I generate one apart from crashing the game?

**Comment by Aflaungos** [comment]
Actually, the issue is on the game itself I guess.
https://bugs.mojang.com/browse/MC-165208

**Comment by florensie** [comment]
Oh wow, thank you for having figured this out yourself. If you ever need to know how to find your logs in the future, here is a tutorial from the Fabric wiki: https://fabricmc.net/wiki/player:tutorials:logs_ml:windows
