### ISSUE TITLE
Support to skip rendering in first person

### ISSUE THREAD

**Issue by rottakore** [florensie/artifacts-fabric#90]
**Is your feature request related to a problem? Please describe.**
This mod is horrible to use with firstpersonmodel mod, the moment you find a hat or a head piece

**Describe the solution you'd like**
Option to skip rendering some pieces in first person

**Additional context**
![image](https://github.com/florensie/artifacts-fabric/assets/88859658/5415da1b-ed81-4537-bdeb-8fe766b95a47)
![image](https://github.com/florensie/artifacts-fabric/assets/88859658/32364b27-7edc-4e35-8932-71c0ba334484)

**Comment by florensie** [comment]
This seems more like something that should be fixed in the third person viewmodel mod. Either way, this repository is no longer under active development. Development of the Fabric version of Artifacts has been consolidated with the Forge version here: https://github.com/ochotonida/artifacts.
